const fs=require('node:fs');
const assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const path=require('node:path');
const os=require('node:os');
const {spawn}=require('node:child_process');
const source=process.argv[2];
if(!source){console.error('Usage: node tests/verify_ui.cjs PATH_TO_PRESET_LOADOUT');process.exit(2);}
const codeRoot=path.resolve(__dirname,'..');
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'alis-ui-'));
const testRoot=path.join(temporary,'preset-loadout');
fs.cpSync(path.resolve(source),testRoot,{recursive:true});
const server=spawn(process.env.ALIS_TEST_PYTHON||'python',[path.join(codeRoot,'app.py'),testRoot,'--port','5053','--no-browser'],{stdio:['ignore','pipe','pipe']});
let serverOutput='';server.stdout.on('data',d=>serverOutput+=d);server.stderr.on('data',d=>serverOutput+=d);
server.on('error',e=>serverOutput+=String(e));
const base='http://127.0.0.1:5053';
const target=path.join(testRoot,'CAS1','weaponstation1','Center Pylon.json');
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function until(pred){for(let i=0;i<150;i++){if(pred())return;await pause(20);}throw new Error('Timed out waiting for UI state');}
(async()=>{
let ready=false;for(let i=0;i<100;i++){try{if((await fetch(base)).ok){ready=true;break;}}catch{}await pause(50);}
if(!ready)throw new Error('Test server not reachable: '+serverOutput);
const html=await(await fetch(base)).text();
const dom=new JSDOM(html,{url:base,runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,d=w.document;
let promptCount=0;w.confirm=()=>{promptCount++;return false;};
w.fetch=(path,options={})=>fetch(new URL(path,base),options);
w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};
w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};
const js=fs.readFileSync(path.join(codeRoot,'static','app.js'),'utf8');
w.eval(js);
const $=id=>d.getElementById(id);
const click=node=>{assert(node,'Missing control');node.click();};
const type=(node,text)=>{node.value=text;node.dispatchEvent(new w.Event('input',{bubbles:true}));};
const check=(node,on)=>{assert(node,'Missing checkbox');node.checked=on;node.dispatchEvent(new w.Event('change',{bubbles:true}));};
await until(()=>$('draft-status').textContent==='SYNCED'&&$('station-name').textContent==='Internal 35mm Autocannons');
assert.equal($('platform-total').textContent,'32');assert.equal($('mount-total').textContent,'986');
assert.equal(d.querySelectorAll('.platform-item').length,32);
assert.equal(d.querySelectorAll('.weapon-row').length,986);
assert.equal($('platform-name').textContent,'A-19 Brawler');assert.equal($('platform-id').textContent,'CAS1');
assert.equal($('layout-status').textContent,'SCHEMATIC / APPROXIMATE');
assert.equal(d.querySelectorAll('#platform-map .map-marker[data-station="0"]').length,2);
assert.equal(d.querySelectorAll('#platform-map .map-marker.selected').length,2);
type($('platform-search'),'Brawler');assert.equal(d.querySelectorAll('.platform-item').length,1);
type($('platform-search'),'CAS1');assert.equal(d.querySelectorAll('.platform-item').length,1);type($('platform-search'),'');
d.querySelector('#platform-map .map-marker[data-station="1"]').dispatchEvent(new w.MouseEvent('click',{bubbles:true}));
await until(()=>$('station-name').textContent==='Center Pylon'&&$('draft-status').textContent==='SYNCED');
const original=fs.readFileSync(target);
type($('weapon-search'),'AAM1_single');
assert(d.querySelectorAll('.weapon-row').length<986);
const input=()=>[...d.querySelectorAll('.weapon-row input')].find(n=>n.getAttribute('aria-label').endsWith('(AAM1_single)'));
assert.equal(input().checked,false);check(input(),true);
assert.equal($('change-count').textContent,'1 pending change');assert.equal($('review').disabled,false);
assert(fs.readFileSync(target).equals(original));
click([...d.querySelectorAll('.station-item')].find(n=>n.querySelector('.station-index').textContent==='02'));
assert.equal(promptCount,1);assert.equal($('station-name').textContent,'Center Pylon');
click($('review'));await until(()=>!$('confirm-save').disabled);
assert($('review-dialog').hasAttribute('open'));assert($('review-changes').textContent.includes('AAM1_single'));
assert(fs.readFileSync(target).equals(original));
click($('confirm-save'));await until(()=>$('message').textContent.startsWith('Saved and verified.')&&$('draft-status').textContent==='SYNCED');
assert(JSON.parse(fs.readFileSync(target,'utf8')).allowedWeapons.includes('AAM1_single'));
assert.equal($('change-count').textContent,'No pending changes');
click($('backups'));await until(()=>$('backup-dialog').hasAttribute('open'));
assert.equal(d.querySelectorAll('.backup-row').length,1);
click(d.querySelector('.backup-row button'));await until(()=>!$('confirm-save').disabled);
assert.equal($('confirm-save').textContent,'Restore station');
click($('confirm-save'));await until(()=>!$('review-dialog').hasAttribute('open')&&$('draft-status').textContent==='SYNCED');
assert(fs.readFileSync(target).equals(original));
// Owner and enabled views do not alter the underlying whitelist.
type($('weapon-search'),'');$('owner-filter').value='vanilla';$('owner-filter').dispatchEvent(new w.Event('change'));
assert([...d.querySelectorAll('.weapon-owner')].every(n=>n.textContent==='vanilla'));
$('owner-filter').value='';$('owner-filter').dispatchEvent(new w.Event('change'));
click(d.querySelector('[data-filter="enabled"]'));
assert.equal(d.querySelectorAll('.weapon-row').length,2);
click(d.querySelector('[data-filter="all"]'));type($('weapon-search'),'AAM1_single');check(input(),true);
// A stale station revision is rejected while the draft remains in the DOM.
const external=JSON.stringify({allowedWeapons:['AAM2_single'],externalField:true});fs.writeFileSync(target,external);
click($('review'));await until(()=>!$('review-error').classList.contains('hidden'));
assert($('review-error').textContent.includes('changed on disk'));
assert.equal(fs.readFileSync(target,'utf8'),external);
click($('cancel-review'));click($('discard'));fs.writeFileSync(target,original);
click($('reload-all'));await until(()=>$('station-name').textContent==='Internal 35mm Autocannons'&&$('draft-status').textContent==='SYNCED');
// Emptying a whitelist requires a separate checkbox in the review.
click(d.querySelector('[data-filter="enabled"]'));type($('weapon-search'),'');
for(const node of [...d.querySelectorAll('.weapon-row input')])check(node,false);
click($('review'));assert(!$('empty-consent').classList.contains('hidden'));assert.equal($('confirm-save').disabled,true);
check($('allow-empty'),true);await until(()=>!$('confirm-save').disabled);
check($('allow-empty'),false);assert.equal($('confirm-save').disabled,true);
click($('cancel-review'));click($('discard'));
assert(fs.readFileSync(target).equals(original));
// Layout editing can be saved while an independent weapon draft remains unsaved.
const gameFiles=()=>{const result={};function walk(folder){for(const entry of fs.readdirSync(folder,{withFileTypes:true})){if(entry.name==='.alis')continue;const full=path.join(folder,entry.name);if(entry.isDirectory())walk(full);else if(!entry.name.endsWith('.bak'))result[path.relative(testRoot,full)]=fs.readFileSync(full).toString('base64');}}walk(testRoot);return result;};
const beforeLayout=gameFiles();
check(d.querySelector('.weapon-row input'),false);assert.equal($('draft-status').textContent,'DRAFT');
click($('edit-layout'));assert($('layout-dialog').hasAttribute('open'));
assert.equal($('layout-name').value,'A-19 Brawler');
type($('layout-name'),'My A-19 Brawler');
$('layout-station').value='2';$('layout-station').dispatchEvent(new w.Event('change'));
assert.equal($('layout-point').options.length,2);
$('layout-point').value='1';$('layout-point').dispatchEvent(new w.Event('change'));
$('layout-x').value='72.4';$('layout-x').dispatchEvent(new w.Event('change'));
$('layout-y').value='61.2';$('layout-y').dispatchEvent(new w.Event('change'));
click($('add-marker'));assert.equal($('layout-point').options.length,3);
click($('remove-marker'));assert.equal($('layout-point').options.length,2);
check($('layout-verified'),true);click($('save-layout'));
await until(()=>!$('layout-dialog').hasAttribute('open'));
assert.equal($('platform-name').textContent,'My A-19 Brawler');assert.equal($('platform-id').textContent,'CAS1');
assert.equal($('layout-status').textContent,'USER CHECKED');assert.equal($('draft-status').textContent,'DRAFT');
const profiles=JSON.parse(fs.readFileSync(path.join(testRoot,'.alis','platforms.json'),'utf8'));
assert.deepEqual(profiles.platforms.CAS1.stations['2'].points[1],[0.724,0.612]);
assert.deepEqual(gameFiles(),beforeLayout);
assert.equal(d.querySelector('#platform-map .map-marker[data-station="2"][data-point="1"]').getAttribute('transform'),'translate(724 612)');
click($('discard'));click($('reload-all'));await until(()=>$('platform-name').textContent==='My A-19 Brawler'&&$('draft-status').textContent==='SYNCED');
// A second session's profile changes are rejected without losing the draft.
click($('edit-layout'));type($('layout-name'),'Unsaved layout');
const externalProfiles=JSON.parse(fs.readFileSync(path.join(testRoot,'.alis','platforms.json'),'utf8'));
externalProfiles.platforms.CAS1.display_name='Outside name';fs.writeFileSync(path.join(testRoot,'.alis','platforms.json'),JSON.stringify(externalProfiles));
click($('save-layout'));await until(()=>!$('layout-error').classList.contains('hidden'));
assert($('layout-error').textContent.includes('another session'));assert.equal($('layout-name').value,'Unsaved layout');
assert($('layout-dialog').hasAttribute('open'));
w.confirm=()=>true;click($('cancel-layout'));click($('reload-all'));await until(()=>$('platform-name').textContent==='Outside name'&&$('draft-status').textContent==='SYNCED');
// Unmapped modded platforms can acquire a name and marker, using their internal API ID.
type($('platform-search'),'Aryx_CargoPlane1');click(d.querySelector('.platform-item'));
await until(()=>$('platform-id').textContent==='Aryx_CargoPlane1'&&$('draft-status').textContent==='SYNCED');
assert.equal($('layout-status').textContent,'UNMAPPED');assert.equal(d.querySelectorAll('#platform-map .map-marker').length,0);
click($('edit-layout'));type($('layout-name'),'Cargo Test');click($('add-marker'));
$('layout-shape').value='transport';$('layout-shape').dispatchEvent(new w.Event('change'));click($('save-layout'));
await until(()=>!$('layout-dialog').hasAttribute('open'));
assert.equal($('platform-name').textContent,'Cargo Test');assert.equal(d.querySelectorAll('#platform-map .map-marker').length,1);
assert.equal($('layout-status').textContent,'SCHEMATIC / APPROXIMATE');assert.deepEqual(gameFiles(),beforeLayout);
console.log('PASS: UI state/events over real Flask HTTP: friendly/internal name search; paired SVG selection; whitelist draft/review/save/exact restore/conflict/empty consent; numeric marker edit/add/remove; profile save/reload/conflict; independent weapon draft; unmapped mod platform naming/layout; unchanged game files during layout saves.');
console.log('Rendered layout, image decoding, pointer geometry and native dialogs were not tested; dialogs were stubbed for DOM tests.');
dom.window.close();
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>{server.kill('SIGINT');server.once('exit',()=>fs.rmSync(temporary,{recursive:true,force:true}));});
